### ISSUE TITLE
Emulator choices are wrong when running playlist buddy

### ISSUE THREAD

**Issue by Bboy486** [markwkidd/ahk-retroarch-playlist-helpers#6]
When I run this utility it creates the playlist but it does not give me the ability to assign the correct emulator to the rom type.

**Comment by markwkidd** [comment]
You do that in RetroArch, in the Settings->Playlists menu. You can also do it in the frontend on a game-by-game basis the first time you try to play the game.

Finally, you can also associate a core within the Playlist Buddy GUI by hardcoding the path to the core you are using in the appropriate field. That's probably the least elegant of the three options, but it's a pretty comprehensive set of ways to accomplish this.

**Comment by Bboy486** [comment]
I did setup the playlist in RetroArch but when I go to select a game the core i need does not display.

Option 2 works but not with ArchBrowser frontend as I need to manually select each time. Is there a way to associate filetypes with the playlists your utility creates?

Since I am using AndroidTV and I am not rooted I do not have access to see the core directory. the path in Retroarch is \\SHIELD\internal\Android\data\user\0\com.retroarch so that is what i put in playlist to path but didnt do anything.

**Comment by markwkidd** [comment]
You can associate a core within the Playlist Buddy GUI by hardcoding the path to the core you are using in the appropriate field.

**Comment by markwkidd** [comment]
Open up a different playlist that is associated with a core, or that has at least one entry that's associated with a core. Get the path from there.

**Comment by markwkidd** [comment]
It's different on a system by system basis. That's why having a field in the Playlist Buddy where you can enter the path manually is the only way to support all of the different systems. RA on a PS2 vs desktop vs android all put the cores in different paths.

**Comment by Bboy486** [comment]
underestood. when i set the path to the same directory as another playlist i get \data\user\0\com.retroarch\cores\DETECTDETECTSNES.lpl

I dont think detect should be twice and it still does not load the core.

In the original SNES core this is the path /data/user/0/com.retroarch/core/snes9x2010_libretro_android.so

**Comment by Bboy486** [comment]
manually this worked /SNES/Chrono Trigger.zip 
Chrono Trigger/data/user/0/com.retroarch/cores/snes9x2010_libretro_android.soSnes9x 2010 09E85EA6|crcNintendo - SNES.lpl/

**Comment by markwkidd** [comment]
use the path to the other core as your template
if the path of a different known working core is `/data/user/0/com.retroarch/core/` then use that as the base of your path and at the end of it add `filename_of_your_selected_core.so`

**Comment by markwkidd** [comment]
if you are trying to manually associate a core with a playlist, you are taking DETECT completely out of the core entry in the playlist

**Comment by Bboy486** [comment]
i did that but detect is being added
\data\user\0\com.retroarch\cores\snes9x2010_libretro_android.soDETECTDETECTSNES.lpl

**Comment by markwkidd** [comment]
DETECT is being added by what?

**Comment by markwkidd** [comment]
![screenshot 2019-01-05 20 48 57](https://user-images.githubusercontent.com/19554678/50731140-622ea200-112b-11e9-950c-96a625efd71d.png)

This is how playlist buddy looks when manually associating a playlist with the mame2003-plus binary on a Lakka system I built recently. Yours should have different paths but look similar. That's all I can say.

**Comment by Bboy486** [comment]
Detect is being added to the path in the lpl playlist file. 

I added the path (and core extension for SNES
I ran the utility and the path adds DETECTDETECTSNES.lpl

\data\user\0\com.retroarch\cores\snes9x2010_libretro_android.soDETECTDETECTSNES.lpl

**Comment by markwkidd** [comment]
Are you saying that the utility adds DETECT to the path to the core?

Please post a screenshot of your settings like I have done.

**Comment by Bboy486** [comment]
![playlistbuddy](https://user-images.githubusercontent.com/16495657/50731228-172a8400-1157-11e9-9813-df2e483ee008.png)

**Comment by markwkidd** [comment]
As the GUI says above the box, the path to the core ends in .so or .dll. For non-Windows, it's .so

Your path setting should probably be `/data/user/0/com.retroarch/cores/snes9x2010_libretro_android.so/` but again it should match exactly the core line from a working playlist.

You have the name of the playlist and the CRC mixed in the path setting. Just the path to the core goes in that box and nothing else. 

Also, your path should use forward slashes if it is going onto a non-Windows device.

Also, please make sure you are using a text editor which understands non-Windows text files to look at these playlists, not Windows notepad. Something like notepad++.

**Comment by Bboy486** [comment]
appreciate the assistance. i made those changes and it finds all the roms but back to my initial issue that the core is not an option when selecting. thanks anyway.

**Comment by Bboy486** [comment]
I found out the issue. Your utility does not like mounted locations.

My ROMs directory is at //COMPUTER/Emulators and ROMS/ROMS/Consoles Video Games/ but the utility does not like // 

in other playlist the actual path was /storage/COMPUTER/Emulators and ROMS/ROMS/Consoles Video Games/

So i did a find a replace and everything works now.

**Comment by markwkidd** [comment]
I'm glad that you found the answer and that you posted about how you solved
it.
